package com.job.board.jobs.model.pojo;

public class ApplicationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.candidateId
     *
     * @mbg.generated
     */
    private Integer candidateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.jobId
     *
     * @mbg.generated
     */
    private Integer jobid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.id
     *
     * @return the value of application.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.id
     *
     * @param id the value for application.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.candidateId
     *
     * @return the value of application.candidateId
     *
     * @mbg.generated
     */
    public Integer getCandidateid() {
        return candidateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.candidateId
     *
     * @param candidateid the value for application.candidateId
     *
     * @mbg.generated
     */
    public void setCandidateid(Integer candidateid) {
        this.candidateid = candidateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.jobId
     *
     * @return the value of application.jobId
     *
     * @mbg.generated
     */
    public Integer getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.jobId
     *
     * @param jobid the value for application.jobId
     *
     * @mbg.generated
     */
    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }
}