package com.job.board.jobs.model.pojo;

import java.util.Date;

public class Application extends ApplicationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.dateApplied
     *
     * @mbg.generated
     */
    private Date dateapplied;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.dateStatusUpdated
     *
     * @mbg.generated
     */
    private Date datestatusupdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.status
     *
     * @return the value of application.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.status
     *
     * @param status the value for application.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.dateApplied
     *
     * @return the value of application.dateApplied
     *
     * @mbg.generated
     */
    public Date getDateapplied() {
        return dateapplied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.dateApplied
     *
     * @param dateapplied the value for application.dateApplied
     *
     * @mbg.generated
     */
    public void setDateapplied(Date dateapplied) {
        this.dateapplied = dateapplied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.dateStatusUpdated
     *
     * @return the value of application.dateStatusUpdated
     *
     * @mbg.generated
     */
    public Date getDatestatusupdated() {
        return datestatusupdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.dateStatusUpdated
     *
     * @param datestatusupdated the value for application.dateStatusUpdated
     *
     * @mbg.generated
     */
    public void setDatestatusupdated(Date datestatusupdated) {
        this.datestatusupdated = datestatusupdated;
    }
}